[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "opay-python"
version = "0.0.3"
authors = [
  { name="Isaac Robert", email="isaacrobertoluwaseun@gmail.com" },
]
description = "A Python client for the OPay API"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/isaacrobert33/OPay-python"
"Bug Tracker" = "https://github.com/isaacrobert33/OPay-python/issues"